# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'PingMonitor_design.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PySide2 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(600, 400)
        Form.setMinimumSize(QtCore.QSize(600, 400))
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.splitter = QtWidgets.QSplitter(Form)
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName("splitter")
        self.layoutWidget = QtWidgets.QWidget(self.splitter)
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.tblIPs = QtWidgets.QTableWidget(self.layoutWidget)
        self.tblIPs.setObjectName("tblIPs")
        self.tblIPs.setColumnCount(2)
        self.tblIPs.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tblIPs.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblIPs.setHorizontalHeaderItem(1, item)
        self.verticalLayout_2.addWidget(self.tblIPs)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btnStart = QtWidgets.QPushButton(self.layoutWidget)
        self.btnStart.setObjectName("btnStart")
        self.horizontalLayout.addWidget(self.btnStart)
        self.lblstatus = QtWidgets.QLabel(self.layoutWidget)
        self.lblstatus.setObjectName("lblstatus")
        self.btnStop = QtWidgets.QPushButton(self.layoutWidget)
        self.btnStop.setObjectName("btnStop")
        self.horizontalLayout.addWidget(self.btnStop)
        self.horizontalLayout.addWidget(self.lblstatus)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.btnTracert = QtWidgets.QPushButton(self.layoutWidget)
        self.btnTracert.setObjectName("btnTracert")
        self.horizontalLayout.addWidget(self.btnTracert)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.btnSettings = QtWidgets.QPushButton(self.layoutWidget)
        self.btnSettings.setObjectName("btnSettings")
        self.horizontalLayout.addWidget(self.btnSettings)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.layoutWidget1 = QtWidgets.QWidget(self.splitter)
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.layoutWidget1)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.txtLog = QtWidgets.QPlainTextEdit(self.layoutWidget1)
        self.txtLog.setMinimumSize(QtCore.QSize(0, 35))
        self.txtLog.setObjectName("txtLog")
        self.verticalLayout.addWidget(self.txtLog)
        self.verticalLayout_3.addWidget(self.splitter)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "PingMonitor"))
        item = self.tblIPs.horizontalHeaderItem(0)
        item.setText(_translate("Form", "IP-адрес"))
        item = self.tblIPs.horizontalHeaderItem(1)
        item.setText(_translate("Form", "Статус"))
        self.btnStart.setText(_translate("Form", "Старт"))
        self.btnStop.setText(_translate("Form", "Стоп"))
        self.btnTracert.setText(_translate("Form", "Tracert"))
        self.btnSettings.setText(_translate("Form", "Настройки"))
        self.label.setText(_translate("Form", "Лог:"))
        self.lblstatus.setText(_translate("Form", "Стоп"))
